config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :content, presence: true, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :get_id_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if params[:back]
      render "new"
    else
      if @blog.save
        redirect_to blogs_path, notice: "投稿が完了しました"
      else
        render "new"
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "投稿内容を編集しました"
    else
      render "edit"
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
    render "new" if @blog.invalid?
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "投稿を削除しました"
  end

  private

  def blog_params
    params.require(:blog).permit(:content)
  end

  def get_id_blog
    @blog = Blog.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def junction_new_or_edit
    if action_name == "new" || action_name == "confirm" || action_name == "create"
      confirm_blogs_path
    elsif action_name == "edit"
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: junction_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div class="error_explanation">
      <% @blog.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  <div class="blog_content">
    <%= form.label :content %><br>
    <%= form.text_area :content, size: "80x6" %>
  </div>
  <div class="button_place">
    <span class="submit_buttton"><%= form.submit %></span>
  </div>
<% end %>

<p class="to_other_page"><%= link_to '一覧画面に戻る', blogs_path %></p>

app/views/blogs/confirm.html.erb
<h2>以下の内容で投稿する</h2>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文</p>
  <p><%= @blog.content %></p>
  <div class="button_place">
    <span class="submit_buttton"><%= form.submit "投稿する" %></span>
    <span class="submit_buttton"><%= form.submit "戻る", name: "back" %></span>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h2>投稿内容を編集する</h2>

<%= render "form" %>

app/views/blogs/index.html.erb
<h2>投稿一覧</h2>

<p><%= notice %></p>

<div class="table_wrapper">
  <table class="table_container">
    <tr>
      <th class="content_header">内容</th>
      <th class="content_header">詳細</th>
      <th class="content_header">更新</th>
      <th class="content_header">削除</th>
    </tr>

  <% @blogs.each do |blog| %>
    <tr>
      <td class="post_content"><%= blog.content %></td>
      <td class="option_order"><%= link_to "投稿を表示", blog_path(blog.id) %></td>
      <td class="option_order"><%= link_to "投稿を編集する", edit_blog_path(blog.id) %></td>
      <td class="option_order"><%= link_to "投稿を削除する", blog_path(blog.id), method: :delete, data: { confirm: "本当に削除しますか？"} %></td>
    </tr>
  <% end %>
  </table>
</div>
<p class="to_other_page"><%= link_to '新しく投稿する', new_blog_path, class:'to_other_page_txt' %></p>

app/views/blogs/new.html.erb
<h2>新たな投稿を作成する</h2>

<%= render "form" %>

app/views/blogs/show.html.erb
<h2>詳細を見る</h2>
<p>投稿内容</p>
<p><%= @blog.content %></p>

<p class="to_other_page"><%= link_to '一覧画面に戻る', blogs_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MONOLOGUEEE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <div class="header_container">
           <h1 id="header_title"><%= image_tag 'owlbird.png', class:'monologueee_icon' %>MONOLOGUEEE</h1>
        </div>
      </header>
      <main>
        <div class="main_container">
          <%= yield %>
        </div>
      </main>
      <footer>
        <div class="footer_container">
          <p><small>(C)2019 MONOLOGUEEE. All Rights Reserved.</small></p>
        </div>
      </footer>
    </div>
  </body>
</html>